### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by amirparto1** [getsurfboard/surfboard#92]
When updating from this subscription link: https://free.iam7.tk/sip002/sub

It says "java.lang.NullPointerException"
This link is working on other applications like V2RAY and Matsury.

**Comment by getsurfboard** [comment]
Fixed

**Comment by amirparto1** [comment]
> Fixed

The problem still exists
![Screenshot_2023-04-20-00-31-30-252_com.getsurfboard.jpg](https://user-images.githubusercontent.com/48597503/233199184-86af228f-9d8e-41f5-9e6e-fc05d9f76bc6.jpg)

**Comment by getsurfboard** [comment]
Will be released in next version, which is 2.20.8
